cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'awscli'
brew 'fzf'
brew 'git'
brew 'imagemagick'
brew 'jq'
brew 'node'
brew 'postgresql'
brew 'python3'
brew 'readline'
brew 'redis'
brew 'terraform'
brew 'vim'
brew 'zsh'

cask '1password'
cask 'google-chrome'
cask 'gimp'
cask 'handbrake'
cask 'iterm2'
cask 'kdiff3'
cask 'openoffice'
cask 'simplenote'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'steam'
cask 'the_silver_searcher'
cask 'tunnelblick'
cask 'vlc'
